version: "2"

services:

  mongo:
    image: mongo
    volumes:
      - /var/lib/mongodb:/data/db:rw

  flask:
    build: .
    volumes:
      - /jalpc/ztool-backhend-mongo:/jalpc
    depends_on:
      - mongo
    env_file:
      - ./.env

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /jalpc/nginx:/etc/nginx:ro
      - /jalpc/ztool-frontend/dist:/usr/share/nginx/html:ro
      - /usr/share/nginx/jack003:/usr/share/nginx/jack003:ro
    depends_on:
      - flask
