version: "2"

services:

  mongo:
    image: mongo
    command: mongod -f /data/configdb/mongodb.conf
    volumes:
      - /data/mongodb:/data/db:rw
      - /jalpc/configdb:/data/configdb:rw

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - /data/redis:/data:rw

  flask:
    build: .
    volumes:
      - /jalpc/ztool-backhend-mongo:/jalpc
    links:
      - mongo
      - redis
    env_file:
      - ./.env

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    volumes:
      - /jalpc/ztool-backhend-mongo:/jalpc
    links:
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /jalpc/nginx:/etc/nginx:ro
      - /jalpc/ztool-frontend/dist:/usr/share/nginx/html:ro
      - /usr/share/nginx/jack003:/usr/share/nginx/jack003:ro
    links:
      - flask
